### ISSUE TITLE
Filtros en Vista de Detalle

### ISSUE THREAD

**Issue by diegocrzt** [nemesiscodex/openfonacide#22]
Visualizaciones de información básica y prioridades
====================================
Se necesitan filtrar la información de aulas, mobiliarios, estado, etc, por Institución y/o por año actualmente la API provee la informacion por establecimiento, esto dificulta mostrar datos solo por institución.

Filtrar detalles por (en la vista de detalles) 
- Año
- Institución

**Comment by yank07** [comment]
Ya esta por institucion, falta por anho

**Comment by yank07** [comment]
Ya esta por anho
