### ISSUE TITLE
Roles

### ISSUE THREAD

**Issue by diegocrzt** [nemesiscodex/openfonacide#28]
Implementar el control de permisos (por roles) para el uso del sistema

**Comment by nemesiscodex** [comment]
Se podria usar
https://docs.djangoproject.com/en/1.7/topics/auth/customizing/#custom-permissions

con algo parecido a 
```html
{% if 'permiso1' in perms.openfonacide %}
    <button> ... </button>
{% endif %}
```

Esto esta implementado ya en #34
