### ISSUE TITLE
Agregar lista  instituciones de filtrado en el sidebar derecho

### ISSUE THREAD

**Issue by yank07** [nemesiscodex/openfonacide#47]

**Comment by nemesiscodex** [comment]
Nose si es buena idea agregar al sidebar derecho.
Pero si necesitamos una pagina donde se muestren todos los resultados

**Comment by nemesiscodex** [comment]
#69

**Comment by diegocrzt** [comment]
Se cierra en #69, se decide separar la lista de resutlados del sidebar derecho
