### ISSUE TITLE
Unificar los filtros

### ISSUE THREAD

**Issue by nemesiscodex** [nemesiscodex/openfonacide#51]
El filtro del mapa y el filtro del resumen

**Comment by nemesiscodex** [comment]
Siguiendo el modelo del filtro del mapa, que les parece esto @diegocrzt @yank07 ?
![screenshot from 2015-04-27 23 49 07](https://cloud.githubusercontent.com/assets/3976562/7362513/f4bee290-ed37-11e4-805f-1fa889746074.png)

esto iria en #29

**Comment by yank07** [comment]
Me parece bien! esta lindo! a Gisse tambien le gusta

**Comment by diegocrzt** [comment]
queda el #29 para terminar la implementación del backend de resumen
